# Database configuration
DB_HOST = "localhost"
DB_USER = "root"
DB_PASSWORD = "Shubham$321"
DB_NAME = "cv"

# NLTK data path (if needed)
NLTK_DATA = "/usr/local/share/nltk_data/"

# Other environment variables
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "true"
PYTHONIOENCODING = "utf-8"
